server:
  port: 8192
  servlet:
    context-path: /store-auth
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
