server:
  port: 8192
  servlet:
    context-path: /store-auth
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
