server:
  port: 8191
  servlet:
    context-path: /store-cart

integrations:
  product-service:
    url: http://localhost:8190/store-core
    connect-timeout: 5000
    read-timeout: 15000
    write-timeout: 5000

